pipeline {
    
    agent {
        docker {
            image 'python:3.9.21-alpine3.21'
        }
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git branch: 'main', 
                url: 'https://github.com/cloudhein/Jenkins-Playground.git'
           }
        }

        stage('Install Depedencies'){
            steps{
                script{
                    sh '''
                    python -m venv venv
                    venv/bin/pip install --upgrade pip
                    venv/bin/pip install flask
                    '''
                }
            }
        }

        stage('Run Tests'){
           steps{
                script{
                    sh '''
                    cd python-app
                    ../venv/bin/python app.py &
                    '''
                }
            }
        }
        
    }
}